version: '3.9'
services:
  ssh.cyrhades.com:
    build: ssh
  webssh.cyrhades.com:
    build: webssh
    ports:
    - "80:8888"
  harmless.cyrhades.com:
    image: anssi/fcsc2019-pwn-harmless:latest
    ports:
      - "4000:4000"